# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190413_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods/other/', verbose_name='图片'),
        ),
    ]
